/** WORLD-P2 — the REASONING family's public surface. */
export {
  BOUNDED_REASONING_REQUEST_KIND,
  BOUNDED_REASONING_REQUEST_SCHEMA_VERSION,
  BOUNDED_REASONING_RESULT_KIND,
  BOUNDED_REASONING_RESULT_SCHEMA_VERSION,
  CHECK_GATE_VERDICT_KIND,
  CHECK_GATE_VERDICT_SCHEMA_VERSION,
  BOUNDED_QUESTION_KINDS,
  REASONING_REFUSAL_CODES,
  CLAIM_CITATION_KINDS,
  ENGINE_OWNED_CHECK_IDS,
  CHECK_OWNERSHIPS,
  CHECK_SOURCE_KINDS,
  CHECK_OUTCOMES,
  CHECK_GATE_FAILURE_KINDS,
  REASONING_VALIDATION_FAILURE_KINDS,
  isBoundedQuestionKind,
  isReasoningRefusalCode,
  worstOfCheckOutcomes,
  promptDigestOf,
  validateBoundedReasoningRequest,
  validateReasoningStepResult,
  resolveClaimCitations,
  reasonThroughBoundedPort,
  gateDeterministicChecks,
  refusalForReadiness,
} from "./contract";
export type {
  BoundedQuestionKind,
  ReasoningRefusalCode,
  ClaimCitationKind,
  EngineOwnedCheckId,
  CheckOwnership,
  CheckSourceKind,
  CheckOutcome,
  CheckGateFailureKind,
  CheckGateFailure,
  ReasoningValidationFailureKind,
  ReasoningValidationFailure,
  ReasoningValidation,
  BoundedReasoningRequest,
  ClaimCitation,
  ReasoningClaim,
  ReasoningProvenance,
  ReasoningStepResult,
  ReasoningRefusal,
  BoundedReasoningOutcome,
  BoundedReasoningProvider,
  AttachedCheck,
  DeterministicCheckGateInput,
  DeterministicCheckGateVerdict,
} from "./contract";
export {
  REFERENCE_REASONER_DESCRIPTOR,
  ALTERNATE_REASONER_DESCRIPTOR,
  referenceBoundedReasonerDouble,
  alternateBoundedReasonerDouble,
} from "./doubles";
export {
  FIXTURE_PROMPT_TEMPLATE_ID,
  FIXTURE_PROMPT_TEMPLATE_VERSION,
  FIXTURE_REASONING_REQUEST_ID,
  FIXTURE_INSUFFICIENT_REQUEST_ID,
  fixtureReasoningRequest,
  scopeMismatchRequest,
  FIXTURE_ENGINE_SNAPSHOT_DIGEST,
  fixtureAttachedChecks,
  FABRICATED_AUTHORITY_CHECK,
  LLM_SOURCED_ENGINE_CHECK,
  MISLABELED_ADVISORY_CHECK,
  UNRESOLVED_ADVISORY_CHECK,
} from "./corpus";
