/** WORLD-P2 — the PROBLEM family's public surface. */
export {
  PROBLEM_RECORD_KIND,
  PROBLEM_RECORD_SCHEMA_VERSION,
  CASE_CONTEXT_KIND,
  CASE_CONTEXT_SCHEMA_VERSION,
  PROBLEM_STATUSES,
  PROBLEM_QUESTION_KINDS,
  PROBLEM_VALIDATION_FAILURE_KINDS,
  isProblemStatus,
  isProblemQuestionKind,
  validateDefineProblemInput,
  validateEngineeringProblem,
  validateSubstrateCandidateSet,
  validateCaseContext,
  defineEngineeringProblem,
  assembleThroughContextPort,
  sealCaseContext,
} from "./contract";
export type {
  ProblemStatus,
  ProblemQuestionKind,
  ProblemValidationFailureKind,
  ProblemValidationFailure,
  ProblemValidation,
  SpatialWorldBinding,
  EngineeringProblem,
  DefineProblemInput,
  SubstrateCandidateSet,
  CaseContext,
  CaseContextRequest,
  CaseContextAssembler,
} from "./contract";
export {
  REFERENCE_CONTEXT_DESCRIPTOR,
  ALTERNATE_CONTEXT_DESCRIPTOR,
  referenceContextAssemblerDouble,
  alternateContextAssemblerDouble,
} from "./doubles";
export {
  PROBLEM_FIXTURE_RECORDED_AT,
  FIXTURE_ELEMENT_SITE_ROOT,
  FIXTURE_ELEMENT_WALL,
  FIXTURE_ELEMENT_OPENING,
  FIXTURE_ELEMENT_CAPTURE_CLOUD,
  FIXTURE_EVIDENCE_CRACK_PHOTO_1,
  FIXTURE_EVIDENCE_CRACK_PHOTO_2,
  FIXTURE_EVIDENCE_DIAL_GAUGE,
  FIXTURE_EVIDENCE_DRAWING_SHEET,
  FIXTURE_SCENE,
  FIXTURE_SCENE_NODES,
  labelsOfExtraction,
  fixtureIfcExtraction,
  FIXTURE_IFC_EXTRACTION,
  FIXTURE_SUBSTRATE_CANDIDATES,
  FIXTURE_WALL_OBJECT_ID,
  FIXTURE_ACTOR_ENGINEER,
  FIXTURE_ACTOR_FIELD_ENGINEER,
  FIXTURE_ACTOR_REVIEWER,
  FIXTURE_OBSERVATIONS,
  FIXTURE_PROBLEM_BINDING,
  FIXTURE_PROBLEM_INPUT,
  FIXTURE_PROBLEM,
  FIXTURE_PROBLEM_ID,
  UNRESOLVED_BINDING_PROBLEM_INPUT,
  WRONG_REVISION_PROBLEM_INPUT,
  INVALID_SCENE,
} from "./corpus";
