/**
 * AISE root build (PROD-001; serverless bundle added by PROD-011).
 *
 * `bun run build` — builds every workspace artifact needed by the
 * production-like local start (`bun run start`) AND by the Vercel
 * deployment (vercel.json `buildCommand` runs this same script):
 *
 *   - apps/web: `vite build` → `apps/web/dist` (the served web bundle);
 *   - backend/api: no build artifact for the local runtime — the API runs
 *     its TypeScript sources directly through Bun (`bun run src/main.ts`),
 *     which is the documented runtime contract;
 *   - api/[[...path]].mjs: the ONE catch-all Vercel serverless function —
 *     esbuild-bundled from `api/serverless.ts` into a self-contained ESM
 *     bundle for the Node.js runtime (the repo's Bun-style extensionless
 *     TS imports cannot go through @vercel/node's checker; the pre-bundled
 *     .mjs needs no tracing, no TS check and no node_modules at runtime).
 *
 * Deterministic postcondition: the command fails (exit 1, `BUILD: FAIL`) if
 * any build exits non-zero OR an expected artifact (`apps/web/dist/index.html`,
 * `api/[[...path]].mjs`) is missing afterwards — a build that "succeeds"
 * without producing its artifacts is a failure, not a silent success.
 */

import { existsSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import * as esbuild from "esbuild";

const ROOT = resolve(import.meta.dir, "..");

async function main(): Promise<void> {
  const distIndex = join(ROOT, "apps/web/dist/index.html");

  console.log("build: apps/web (vite build)");
  const proc = Bun.spawnSync({
    cmd: [process.execPath, "run", "build"],
    cwd: join(ROOT, "apps/web"),
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) {
    console.error(`BUILD: FAIL — apps/web build exited with code ${proc.exitCode ?? 1}`);
    process.exit(1);
  }
  if (!existsSync(distIndex)) {
    console.error("BUILD: FAIL — apps/web/dist/index.html missing after build");
    process.exit(1);
  }

  const serverlessSource = join(ROOT, "api", "serverless.ts");
  const serverlessBundle = join(ROOT, "api", "[[...path]].mjs");
  console.log("build: api/[[...path]].mjs (esbuild bundle of api/serverless.ts)");
  const bundle = existsSync(serverlessSource)
    ? await esbuild.build({
        entryPoints: [serverlessSource],
        outfile: serverlessBundle,
        bundle: true,
        platform: "node",
        format: "esm",
        target: "node22",
        legalComments: "none",
        banner: {
          js:
            "/* AISE serverless catch-all — generated by tools/build.ts from api/serverless.ts; DO NOT EDIT (gitignored build artifact). */",
        },
      })
    : null;
  if (bundle === null || bundle.errors.length > 0 || !existsSync(serverlessBundle)) {
    console.error("BUILD: FAIL — api/[[...path]].mjs bundle failed or missing after build");
    process.exit(1);
  }

  console.log(`BUILD: PASS (${relative(ROOT, distIndex)}, ${relative(ROOT, serverlessBundle)})`);
}

await main();
