/**
 * AISE root build (PROD-001; serverless bundle added by PROD-011).
 *
 * `bun run build` — builds every workspace artifact needed by the
 * production-like local start (`bun run start`) AND by the Vercel
 * deployment (vercel.json `buildCommand` runs this same script):
 *
 *   - apps/web: `vite build` → `apps/web/dist` (the served web bundle);
 *   - backend/api: no build artifact for the local runtime — the API runs
 *     its TypeScript sources directly through Bun (`bun run src/main.ts`),
 *     which is the documented runtime contract;
 *   - api/[...path].mjs: the ONE catch-all Vercel serverless function —
 *     COMMITTED as a deploy beacon (Vercel's zero-config/functions scan
 *     needs the file PRE-build; a gitignored artifact only worked when a
 *     restored build cache happened to pre-seed it — the 2026-09-20
 *     lesson). Every build regenerates the bundle deterministically, so
 *     the committed bytes are always refreshed from tracked sources;
 *     esbuild-bundled from `api/_serverless.ts` into a self-contained ESM
 *     bundle for the Node.js runtime (the repo's Bun-style extensionless
 *     TS imports cannot go through @vercel/node's checker; the pre-bundled
 *     .mjs needs no tracing, no TS check and no node_modules at runtime).
 *     The catch-all FILE NAME `[...path]` is Vercel's zero-config REQUIRED
 *     catch-all convention — the route matches EVERY depth under /api/.
 *     (The `[[...path]]` OPTIONAL catch-all spelling is a Next.js convention
 *     the raw function builder does not understand: a real deployment
 *     proved it compiles to a SINGLE-segment route `^/api/([^/]+)$`, which
 *     404s every multi-segment path like /api/v1/gaps.) The source file's
 *     leading underscore (`api/_serverless.ts`) keeps Vercel's zero-config
 *     from picking the TS source up as a second, traced, broken function.
 *
 * Deterministic postcondition: the command fails (exit 1, `BUILD: FAIL`) if
 * any build exits non-zero OR an expected artifact (`apps/web/dist/index.html`,
 * `api/[...path].mjs`) is missing afterwards — a build that "succeeds"
 * without producing its artifacts is a failure, not a silent success.
 */

import { existsSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import * as esbuild from "esbuild";

const ROOT = resolve(import.meta.dir, "..");

async function main(): Promise<void> {
  const distIndex = join(ROOT, "apps/web/dist/index.html");

  console.log("build: apps/web (vite build)");
  const proc = Bun.spawnSync({
    cmd: [process.execPath, "run", "build"],
    cwd: join(ROOT, "apps/web"),
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) {
    console.error(`BUILD: FAIL — apps/web build exited with code ${proc.exitCode ?? 1}`);
    process.exit(1);
  }
  if (!existsSync(distIndex)) {
    console.error("BUILD: FAIL — apps/web/dist/index.html missing after build");
    process.exit(1);
  }

  const serverlessSource = join(ROOT, "api", "_serverless.ts");
  const serverlessBundle = join(ROOT, "api", "[...path].mjs");
  console.log("build: api/[...path].mjs (esbuild bundle of api/_serverless.ts)");
  const bundle = existsSync(serverlessSource)
    ? await esbuild.build({
        entryPoints: [serverlessSource],
        outfile: serverlessBundle,
        bundle: true,
        platform: "node",
        format: "esm",
        target: "node22",
        legalComments: "none",
        banner: {
          js:
            "/* AISE serverless catch-all — generated by tools/build.ts from api/_serverless.ts; DO NOT EDIT (committed deploy beacon, regenerated deterministically by every build). */",
        },
      })
    : null;
  if (bundle === null || bundle.errors.length > 0 || !existsSync(serverlessBundle)) {
    console.error("BUILD: FAIL — api/[...path].mjs bundle failed or missing after build");
    process.exit(1);
  }

  console.log(`BUILD: PASS (${relative(ROOT, distIndex)}, ${relative(ROOT, serverlessBundle)})`);
}

await main();
