/** WORLD-P2 — the EVIDENCE family's public surface. */
export {
  EVIDENCE_ENVELOPE_KIND,
  EVIDENCE_ENVELOPE_SCHEMA_VERSION,
  MISSING_EVIDENCE_REPORT_KIND,
  MISSING_EVIDENCE_REPORT_SCHEMA_VERSION,
  GAP_KINDS,
  READINESS_VERDICTS,
  REQUIREMENT_KINDS,
  MISSING_EVIDENCE_TASK_STATUSES,
  EVIDENCE_VALIDATION_FAILURE_KINDS,
  EPISTEMIC_RANK,
  isGapKind,
  isReadinessVerdict,
  validateEvidenceEnvelope,
  validateEvidenceRequirement,
  validateMissingEvidenceReport,
  bindProblemEvidence,
  detectThroughEvidencePort,
  worstOfVerdicts,
  verdictOfGapKind,
  buildEvidenceGap,
  sealMissingEvidenceReport,
} from "./contract";
export type {
  GapKind,
  ReadinessVerdict,
  RequirementKind,
  MissingEvidenceTaskStatus,
  EvidenceValidationFailureKind,
  EvidenceValidationFailure,
  EvidenceValidation,
  ProblemEvidenceEnvelope,
  BindEvidenceInput,
  EvidenceSufficiencyRequirement,
  UncertaintyBoundRequirement,
  EpistemicFloorRequirement,
  EvidenceRequirement,
  EvidenceRequirementSet,
  MissingEvidenceTask,
  EvidenceGap,
  RequirementAssessment,
  MissingEvidenceReport,
  MissingEvidenceRequest,
  MissingEvidenceDetector,
} from "./contract";
export {
  REFERENCE_DETECTOR_DESCRIPTOR,
  ALTERNATE_DETECTOR_DESCRIPTOR,
  GAP_DETAILS,
  referenceMissingEvidenceDouble,
  alternateMissingEvidenceDouble,
  detectorRefusal,
} from "./doubles";
export {
  FIXTURE_EVIDENCE_PHOTO_1,
  FIXTURE_EVIDENCE_PHOTO_2,
  FIXTURE_EVIDENCE_DRAWING,
  FIXTURE_EVIDENCE_GAUGE,
  FIXTURE_PROVENANCE_LINKS,
  SCENARIO_A_PROVENANCE_LINKS,
  FIXTURE_BUNDLES,
  SCENARIO_A_BUNDLES,
  FIXTURE_ASSERTION_MATERIAL,
  FIXTURE_ASSERTION_DEFLECTION,
  FIXTURE_ASSERTION_STEEL_SECTION,
  SCENARIO_A_ASSERTIONS,
  SCENARIO_B_ASSERTIONS,
  FIXTURE_MEASUREMENT_DEFLECTION,
  REQ_ID_IMAGERY,
  REQ_ID_STEEL_SECTION,
  REQ_ID_MATERIAL,
  FIXTURE_REQUIREMENT_SET,
  SCENARIO_A_EVIDENCE_INPUT,
  SCENARIO_B_EVIDENCE_INPUT,
  DUPLICATE_EVIDENCE_INPUT,
  UNRESOLVED_LINK_INPUT,
  UNRESOLVED_SUBJECT_INPUT,
  EMPTY_REQUIREMENT_SET,
  UNRESOLVED_SUBJECT_REQUIREMENT_SET,
  BAD_COUNT_REQUIREMENT_SET,
  FIXTURE_ACTOR_FIELD_ENGINEER,
} from "./corpus";
